### PR TITLE
#18 added enum parsing

### LINKED ISSUE #18: Add enum parsing
Something like `CLI.Enum<Weather>(args, "weather")`
* where user input is `"cmd -weather rainy"`
* and `Weather` is:
```cs
        public enum Weather
        {
            Rainy,
            Sunny,
            Cloudy,
        }
```

### PR DESCRIPTION
**Pull request by clee-omega**
added `CLI.ArgToEnum<T>(d, key)`
However, I don't like the naming. But if I leave it as `Enum()` (following the same nomenclature as the other convenience argument-parsing functions) then accessing the `Enum` class would have to be done by calling `System.Enum` in any file that had `using IgniteCLI;`

Therefore, this PR is not complete until a naming decision is made
Thoughts @ctennery-omega ?

Resolves #18

### CODE REVIEW

**Comment by ctennery-omega** [comment]
I don't want to override something as basic as `System.Enum` so I'd prefer another name, even if it's not as pretty.
Could we extend `System.Enum` and make it parse for us?

**Comment by ctennery-omega** [comment]
@clee-omega That sounds like a bad idea when you put it that way lol. I think we should just stick with `CLI.ArgToEnum<T>(d, key)` then.

**Comment by clee-omega** [comment]
I think I'd rather `CLI.StringArg()`, `CLI.IntArg()`, `CLI.BoolArg()`, and `CLI.EnumArg()`
That way when using intellisense, `CLI.S` or `CLI.E` is all that needs to be typed before being able to hit enter to likely get what you want. If we do `ArgToX` the developer has to type more each time, and these are frequently-used methods.

**Comment by Tencona** [comment]
@clee-omega I'm fine with that

**Pull request merged**
